traefik_email: certs@example.com
traefik_domain: traefik.local.example.com
traefik_passwd_file: /var/traefik/passwd
traefik_username: admin
traefik_password: changethis

swarmfile_dir: /swarm

le_dns_auth:
  provider: azure
  credentials:
    - { name: azure_client_id, value: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}
    - { name: azure_client_secret, value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
    - { name: azure_subscription_id, value: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}
    - { name: azure_tenant_id, value: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}
    - { name: azure_resource_group, value: "XXXXXXXX"}

#le_dns_auth:
#  provider: aws
#  credentials:
#    - { name: aws_access_key_id, value: ""}
#    - { name: aws_secret_access_key, value: ""}
#    - { name: aws_region, value: "XXXXX"}
#    - { name: aws_hosted_zone_id, value: "XXXXX"}